# Site settings
title: PROJECT - X
email: galto4ir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Англи хэлийг заавал хэлний курст сурах ёстой юу? Мэдээж үгүй.
  Хэрвээ бид хүсэх л юм бол яаж ч сурч болно. Гэхдээ бидэнд тулгамддаг
  асуудал бол ямар системээр, яаж биеэ дааж хэлээ зөв хөгжүүлэх вэ?
  Энэ асуудлыг PROJECT - X шийднэ.
baseurl: "project-x" # the subpath of your site, e.g. /blog/
url: "http://galto4ir.github.io/" # the base hostname & protocol for your site
project_bg: "img/pro_bg.jpg"
cp: © 2015 Project - X.
# Build settings
markdown: kramdown
